### ISSUE TITLE
create a codebase for face detection system

### ISSUE THREAD

**Issue by VALASALARAKESH** [Google-Developer-Student-Club-MBU/face-detection-system#1]

**Comment by Vybhavigithub** [comment]
@VALASALARAKESH Could you please assign me this task .I would like to contribute.

**Comment by Vybhavigithub** [comment]
@VALASALARAKESH Can I solve this issue using java programming language?

**Comment by Vybhavigithub** [comment]
@VALASALARAKESH I would like to contribute for the documentation . could you please assign(Roll no:21121A05q1)

**Comment by PradeepG-07** [comment]
Could you please assign me this issue
Name: Pradeep
Roll number: 21121A0574
III year cse

**Comment by VALASALARAKESH** [comment]
@PradeepG-07  issue is assigned to you

**Comment by PradeepG-07** [comment]
Hey @VALASALARAKESH I have linked a PR. Please go through it.

**Comment by VALASALARAKESH** [comment]
Are you from Mohan Babu University
